# Application URL
url=https://parabank.parasoft.com/parabank/register.htm

# Browser driver
chromeDriverPath=C:/Users/kbalasubramanian/IdeaProjects/Automation/src/chromedriver.exe

# Screenshot location
screenshotPath=C:\\Users\\kbalasubramanian\\Downloads\\Screenshots

# JSON test data
jsonPath=C:\Users\kbalasubramanian\Automation\Parabank2\src\test\resources\data\Parabank.json


#chromeDriverPath=D:\\TestingB\\BarclaysAutomation\\driver\\chromedriver.exe
#
## Screenshot location
#screenshotPath=C:\\Users\\viji\\IdeaProjects\\ParaBank\src\\test\\Screenshots
#
## JSON test data
#jsonPath=C:\\Users\\psvim\\IdeaProjects\\ParaBank\\src\\test\\resources\\data\\Parabank.json